apiVersion: v1
kind: Service
metadata:
  name: devopsg3-yolo-client-service
spec:
  selector:
    app: devopsg3-yolo-client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000