apiVersion: v1
kind: Service
metadata:
  name: devopsg3-yolo-database-service
spec:
  selector:
    app: devopsg3-yolo-database
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017